# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt6 Dependencies
      run: |
        chmod +x ./script/install-qt6-dependencies.sh
        ./script/install-qt6-dependencies.sh

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-all-dev qt6-base-dev qt6-svg-dev libsqlite3-dev ninja-build default-jdk maven

    - name: Configure CMake with Vcpkg Preset
      run: cmake --preset vcpkg-ninja-release -B build
      working-directory: ${{github.workspace}}


    - name: Build with CMake Preset
      run: cmake --build build --preset vcpkg-ninja-release -v
      working-directory: ${{github.workspace}}

    - name: Run Tests
      run: |
        cd build
        ctest --preset vcpkg-ninja-release
      working-directory: ${{github.workspace}}
